### PR TITLE
Successful configuration for readthedocs

### PR DESCRIPTION
**Pull request by duetosymmetry**
You can see the test build at https://quaternion-rtd-testing.rtfd.io/ .

Specific versions of numpydoc and additional care in the package `setup.py` and `docs/conf.py` was necessary for a successful RTD build (part of this is an upstream bug in numpydoc).

There are also specific configurations on the RTD 'Advanced Settings' page necessary for the build to work, which I can communicate to you in comments below or another channel if desired.

If this PR is merged then I will delete the quaternion-rtd-testing project from RTD.

### CODE REVIEW

**Comment by duetosymmetry** [comment]
This PR addresses issue #110.

**Comment by moble** [comment]
That looks awesome!  Thanks so much, Leo.

Unless you want privacy for some reason, I'd be happy to see the special configuration here — especially because it might be nice as a reference for anyone (e.g., me) who might find this page when trying to get things working on another project.

**Comment by duetosymmetry** [comment]
Ok, here are the relevant settings I have on the Advanced Settings page on RTD:
- Requirements file: requirements-doc.txt
- Python Interpreter: CPython 3.x (default)
- [X] Install Project (checked)
- [X] Use system packages (checked)

**Comment by moble** [comment]
Looking great.  Thanks again!

**Pull request merged**
