### PR TITLE
Add from_cartesian_coords

### PR DESCRIPTION
**Pull request by eelregit**
For an application in cosmology I need on a 3D grid the WignerD rotating from some z direction to each grid point. So this from_cartesion_coords function seems to be the easiest way. I think the algorithm is consistent with the sqrt function or equation A13 of your paper.

In addition I attempted to make the from_spherical_coords consistent with the convention of sqrt, i.e. following a great circle rather than the Euler angle-like convention. And this one should be faster.

Also optimized sqrt a bit.

### CODE REVIEW

**Comment by moble** [comment]
Thank you for your efforts, but there are some major problems with this PR.  Since there are three very different things being done here, it might have been better to break it into three separate PRs.  But since you've already done it, let's take a look.

First, you can't change the definition of `from_spherical_coords` any more than you can redefine `from_euler_angles` to ignore `gamma`, for example.  This function is defined so that the result takes not just `z` onto the point given by the `theta, phi` coordinates (which your version and mine both do equally well), but also `x` and `y` onto the standard `theta` and `phi` basis vectors at that point (which only my version does).  This is crucial, because the Wigner-D matrix and spin-weighted spherical harmonics depend critically on the additional rotation that aligns those basis vectors.  It looks like you could just do `git revert c70f2468 && git push` to remove that from this PR.

Second, I like your changes to the `sqrt` function, except that the result is actually wrong for non-unit quaternions.  The reason is that you've set
```c
double c = sqrt(0.5/(absolute*(absolute+q.w)));
```
It should just be
```c
double c = sqrt(0.5/(absolute+q.w));
```
This can be tested by checking that `sqrt(q)*sqrt(q)` equals `q` for some non-unit quaternion `q`.  I've gone ahead and done this, and as a result found that the first branch in the `sqrt` function (where it just returns `{0,1,0,0}`) needed fixing, so you'll have to rebase to add your corrections.

Finally, I don't understand what value the `from_cartesian_coords` function adds to this module, so I'm inclined not to include it.  I think it's a confusing function (especially with the non-descriptive docstring you gave it), it's not likely to be useful to basically anyone but you, and it's equivalent to the simple
```python
quaternion.quaternion(z, -y, x, 0.0).sqrt()
```
(possibly with a `.normalized()` if that's really what you want).  Especially since it's more common — in my experience, at least — to need an arbitrary vector rotated onto another arbitrary vector (rather than \hat{z} onto some vector), it seems like this is too much of a specialization.  Moreover, if you have a whole grid of these things, you're almost certainly better off just using numpy to construct a float array of the right shape, cast it to quaternion, and take the `sqrt` and maybe `normalized`.

**Comment by moble** [comment]
Thanks @eelregit!

**Comment by eelregit** [comment]
Thanks a lot for the suggestion on using sqrt to do this! And sorry about the extra fuss!

I still don't see why the definition of from_spherical_coords isn't just a convention.
It seems you only used it in the tests and when explaining the implicit angle dependence of SWSH.
Why will this direct rotation not work in those cases? Just curious.

BTW some unrelated questions here. Do you plan to built quaternion into numpy in the future?
I noticed SWSH is about 50% slower than Wigner_D_element, but I thought they are almost the same thing? And somehow the fastest examples shown in the test/ScratchPaper.ipynb is twice as fast as when I timed it on my laptop and clusters. Should one use the jitted inner functions to get that performance then?

**Comment by moble** [comment]
> I still don't see why the definition of from_spherical_coords isn't just a convention.

It *is* just a convention, but it's a convention that already exists and is in use — and not just in my code, or even code that depends on my code.  In the case of a SWSH, those functions already exist and were given their conventional values [in 1966](http://aip.scitation.org/doi/abs/10.1063/1.1931221), and their relationship to Wigner D matrices [in 1967](http://aip.scitation.org/doi/abs/10.1063/1.1705135).  If you plug in *your* version of this quaternion, you'll get the conventional value times some complex phase at almost every point on the sphere.  Of course, that's just one place that the basis vectors are used; they're also used throughout physics, so any time they're needed they can be computed with this function.

> Do you plan to built quaternion into numpy in the future?

I doubt that there's any interest in this on the numpy-developers' side, so not likely.  Python is flexible enough that a package like this can insert itself into numpy, and that's probably good enough.

> I noticed SWSH is about 50% slower than Wigner_D_element, but I thought they are almost the same thing? And somehow the fastest examples shown in the test/ScratchPaper.ipynb is twice as fast as when I timed it on my laptop and clusters. Should one use the jitted inner functions to get that performance then?

Other than overhead, there shouldn't be any significant difference in speeds for these calculations.  So if you're seeing a difference, my guess is that you're calling them on different amounts of data.  For example, if you call `SWSH` a thousand times on one quaternion at a time, it will be far slower than if you call it once on a thousand quaternions.  The reason is that most of the work being done in the former case is in python (which is slow), and is just doing things like checking arguments even though those arguments may be the same each time you call it.  If your use case requires that you call many times on small sets of data, then using the jitted functions directly would probably help a little.  But in any case, if performance is a problem, you need to profile your code.

All that being said, if you need very large `ell` values and/or truly fast calculations of SWSHs or Wigner D matrices, there are better packages out there.  I've designed my code for flexibility because I have an unusual need — to evaluate SWSHs at arbitrary points under weird Lorentz transformations.  But most CMB people, for example, will probably want to use something like [the `spinsfast` package](https://github.com/moble/spinsfast).  That uses different computational techniques for much better speed and accuracy at large `ell`.

**Comment by eelregit** [comment]
Perfect. Thanks a lot for the clear explanations!

Yes you are right about the overhead. The difference in performance in indeed driven by the difference in overhead in those 2 functions. I tested both on a size 10 quaternion array. Once I increase this size to 1000, the difference in performance is gone.

I will try your packages fast. If performance turns out to be an issue. I will probably take your Wigner D expansion and evaluate it with numpy and numexpr, as is done [here](https://github.com/bccp/nbodykit/blob/fc5a0498d18305624d7ceb38ea7346f5776568d4/nbodykit/algorithms/convpower.py#L66). Do you happen to know if this expansion can be simplified or if there exists a simpler algorithm for the direct rotation (along the longitude) from \hat{z} to some other direction?

**Comment by moble** [comment]
> If performance turns out to be an issue. I will probably take your Wigner D expansion and evaluate it with numpy and numexpr

Unless `numba` isn't working for some reason — in which case you should see a warning at some point — then evaluating the formula with numpy and/or numexpr will almost definitely be slower and use more memory.

> Do you happen to know if your expansions (equations 6 and 7 on your page) can be simplified or if there exists a simpler algorithm for the direct rotation (along the longitude) from \hat{z} to some other direction?

The expressions almost certainly can't be simplified further in general.  For a direct rotation, the quaternion will have a zero `z` component so you could set that to zero in the formula and get a minor simplification, though I doubt that it would be worthwhile.

But I really should caution you that direct rotation is not a standard convention.  It's related to the stereographic representation, but different.  So if you're doing this for some project in cosmology, remember that most other people in cosmology use the `theta, phi` convention.  Just be sure you know what you're doing.

**Comment by eelregit** [comment]
Sorry I actually meant sympy+numexpr. That piece of Ylm code is actually faster than the one in scipy.special by a factor of 7~8. But the mileage may vary for WignerD, which is the expensive step in the computation. I also need to do FFT but that should be cheaper.

Thanks for the alert. What I am doing is just measuring the correlation among N (say 3 or 4) galaxies with respect to their common line of sight, for all galaxies. The line of sight changes with the galaxies, so that's why I need to use Wigner D to rotate all lines of sight before summing them up. But there's also rotation symmetry about the line of sight, which means I am indeed free to pick whichever rotation that takes a point on S2 to \hat{z}. In brief, I am project the galaxy correlation function to the scalar component of the multi-polar basis, which is invariant under rotation.

**Pull request merged**
